
server:
  port: 7001

spring:
  application:
    name: demo-client

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

feign:
  hystrix:
    enabled: true

info:
  aa:
    name: "hello"
    email: "hello@ioware.cc"
  bb:
    name: "xyz"


